# Generated by Django 5.0.2 on 2024-04-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0002_moviedata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='type',
            field=models.CharField(default='action', max_length=50),
        ),
    ]
