# Generated by Django 5.0.2 on 2024-04-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0003_alter_moviedata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/None/Noimg.jpg', upload_to='Images/'),
        ),
    ]
